VAGRANTFILE_API_VERSION = "2"

UBUNTU_VERSION = "16.04"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-#{UBUNTU_VERSION}"

  config.vm.provision :shell, inline: $script

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define "master" do |master|
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    master.vm.hostname = "master"
    master.vm.network :private_network, ip: "192.168.33.10"
    master.vm.provision :shell, inline: $master
  end

  config.vm.define "node" do |node|
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    node.vm.hostname = "node"
    node.vm.network :private_network, ip: "192.168.33.11"
    node.vm.provision :shell, inline: $node
  end
end

$script = <<SCRIPT
apt-get update
apt-get upgrade -y
apt-get install -y ntp
SCRIPT

$master = <<MASTER
# kubectl
#curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
#chmod +x ./kubectl
#sudo mv ./kubectl /usr/local/bin/kubectl
MASTER

$node = <<NODE
NODE
