VAGRANTFILE_API_VERSION = "2"

UBUNTU_VERSION = "16.04"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-#{UBUNTU_VERSION}"

  config.vm.provision :shell, inline: $script

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define "master" do |master|
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
    end
    master.vm.hostname = "master"
    master.vm.network :private_network, ip: "192.168.33.10"
    master.vm.provision :shell, privileged: false, inline: $master
  end

  config.vm.define "node" do |node|
    node.vm.hostname = "node"
    node.vm.network :private_network, ip: "192.168.33.11"
    node.vm.provision :shell, privileged: false, inline: $node
  end
end

$script = <<SCRIPT
apt-get update -qq
apt-get upgrade -y
apt-get install -y ntp

# docker
apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update -qq
apt-get install -y docker-ce
usermod -aG docker vagrant

# kubeadm, kubectl, kubelet
apt-get update && apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl

# swapoff
swapoff --all
SCRIPT

$master = <<MASTER
# kubeadm
sudo kubeadm init --pod-network-cidr=10.244.0.0/16
# TODO: token, ip, port, hash

mkdir -p $HOME/.kube
sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# flunnel
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.bridge.bridge-nf-call-iptables=1
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml

# kubectl get pods --all-namespaces
# kubectl taint nodes --all node-role.kubernetes.io/master-
MASTER

$node = <<NODE
# kubeadm join --token $TOKEN ${MASTER_IP}:${MASTER_PORT} --discovery-token-ca-cert-hash sha256:${HASH}
NODE
