Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

#  config.vm.provision :shell, privileged: false, path: "bootstrap.sh"
end
