VAGRANTFILE_API_VERSION = "2"

UBUNTU_VERSION = "18.04"

CPU_COUNT = "2"
RAM = "4096"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-#{UBUNTU_VERSION}"

  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "#{RAM}"
    vb.cpus = "#{CPU_COUNT}"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

#  config.vm.provision :shell, privileged: false, path: "bootstrap.sh"
end
