VAGRANTFILE_API_VERSION = "2"

UBUNTUVERSION = "16.04"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-#{UBUNTUVERSION}"

  config.vm.network :private_network, ip: "192.168.33.20"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision :shell, privileged: false, path: "bootstrap.sh"
end
